/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bottom_bun.glb -t -T 
Files: bottom_bun.glb [26.04KB] > Z:\art\models\burger\bottom_bun-transformed.glb [2.76KB] (89%)
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type {ObjectMap} from "@react-three/fiber";

type GLTFResult = GLTF & ObjectMap & {
  nodes: {
    bottom_bun: THREE.Mesh
  }
  materials: {
    bun: THREE.MeshBasicMaterial
  }
}

export function BunBottom() {
  const { nodes, materials } = useGLTF('/bottom_bun-transformed.glb') as GLTFResult
  return (
    <group dispose={null}>
      <mesh geometry={nodes.bottom_bun.geometry} material={materials.bun} receiveShadow castShadow position={[0, -0.2, 0]} />
    </group>
  )
}

useGLTF.preload('/bottom_bun-transformed.glb')
