/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 top_bun.glb -t -T 
Files: top_bun.glb [18.06KB] > Z:\art\models\burger\top_bun-transformed.glb [2.39KB] (87%)
*/

import * as THREE from 'three'
import {useGLTF} from '@react-three/drei'
import type {GLTF} from 'three-stdlib'
import type {ObjectMap} from "@react-three/fiber";

type GLTFResult = GLTF & ObjectMap & {
    nodes: {
        top_bun: THREE.Mesh
    }
    materials: {
        bun: THREE.MeshBasicMaterial
    }
}

export function BunTop() {
    const {nodes, materials} = useGLTF('/top_bun-transformed.glb') as GLTFResult
    return (
        <group dispose={null}>
            <mesh geometry={nodes.top_bun.geometry} material={materials.bun} position={[0, 0.4, 0]}/>
        </group>
    )
}

useGLTF.preload('/top_bun-transformed.glb')
